### ISSUE TITLE
Napsat teďko do dokumentace přiklad, který můžu zkusit [zápočet]

### ISSUE THREAD

**Issue by fan1x** [goramartin/QueryEngine#2]

**Comment by fan1x** [comment]
Zkouším zadávat query, ale nic to nedělá, takže hádám, že zadávám špatně query....

**Comment by goramartin** [comment]
Napsal jsem kratší readme, kde jsem popsal jak se dělají soubory s daty, a popsal tam jak se tam zadává query, včetně syntaxu. Už je to tady na githubu. Úplně dole jsou nějaké patterny, které můžeš otestovat. 
Do mailu ti ještě pošlu obrázek, jak vypadá graf, který tam teď je.

**Comment by fan1x** [comment]
Jinak není potřeba popisovat PGQL, stačí dát odkaz na dokumentaci... Možná jen popsat, co podporuješ Ty ;)
