### ISSUE TITLE
Co vypisuje program na výstupu? [zápočet]

### ISSUE THREAD

**Issue by fan1x** [goramartin/QueryEngine#4]
Úplně teď nechápu výstup? Tahle query by měla vrátit všechny vrcholy, ze který jde jedna hrana do libovolného vrcholu **a zároveň** z toho vrcholu musí jít hrana zpátky do toho vrcholu...
Tedy pro Tvůj graf by to měly být vrcholy 4 a 7... Co říkají ty další čísla? Co říka ten `:`
```
Enter Query:
SELECT x MATCH (x)->(y),(y)->(x);

Results:
4 14 7 7 17 4
:
7 17 4 4 14 7
:
```

**Comment by goramartin** [comment]
Jak jsem psal v té dokumentaci, že to vypisuje id těch věcí co to matchne v tom patternu. Co to tedy znamená. Je to tedy nějaký cyklus. Ten : neznamený nic, měl jsem to tam jen aby se na to lépe dívalo. Ty čísla znamenají, pro ten první řádek:  matchlo to vrchol s id 4 pak to matchlo hranu 14 a posléze vrchol 7, jelikož je to oddělené, tak to šlo z toho 7 mého vrcholu po hraně 17 a zpátky do vrcholu 4.

**Comment by fan1x** [comment]
Díky, to jsem přehledl 😄
