### ISSUE TITLE
Udělat správně syntaxi pro hrany [zápočet]

### ISSUE THREAD

**Issue by fan1x** [goramartin/QueryEngine#5]
to by mělo být easy 😄

**Comment by fan1x** [comment]
`(x)-[e]->(y)` a `(x)->(y)`

**Comment by goramartin** [comment]
Jasně, hned to udělám

**Comment by goramartin** [comment]
Můžu se zeptat, co je špatně na tom druhém, -> ? Ve specifikaci to mají označené pod názvem "Omit variable name in edge"

**Comment by fan1x** [comment]
Sorry, to druhé je správně, měl to být přiklad jak to máš ty vs. správně

**Comment by goramartin** [comment]
už jsem to předělal
